// <auto-generated />
using System;
using Hmss.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hmss.Api.Migrations
{
    [DbContext(typeof(HmssDbContext))]
    [Migration("20260321173603_Initial create")]
    partial class Initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hmss.Api.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ConversationId", "SentAt");

                    b.HasIndex("RequestId", "SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("Hmss.Api.Entities.Conversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConversationId");

                    b.HasIndex("RequestId");

                    b.HasIndex("TenantId");

                    b.HasIndex("OwnerId", "TenantId")
                        .IsUnique()
                        .HasFilter("[RequestId] IS NULL");

                    b.HasIndex("OwnerId", "TenantId", "RequestId")
                        .IsUnique()
                        .HasFilter("[RequestId] IS NOT NULL");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Hmss.Api.Entities.OwnerVerification", b =>
                {
                    b.Property<Guid>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdDocumentRef")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PersonalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupportingDocsRef")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VerificationId");

                    b.HasIndex("OwnerId");

                    b.ToTable("OwnerVerifications", t =>
                        {
                            t.HasCheckConstraint("CK_OwnerVerification_Status", "Status IN ('PendingReview', 'Verified', 'Rejected')");
                        });

                    b.HasData(
                        new
                        {
                            VerificationId = new Guid("00000000-0000-0000-0000-000000000030"),
                            IdDocumentRef = "seed/id-document-owner1.pdf",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            PersonalInformation = "Demo Owner – ID verified for seeding purposes.",
                            ReviewNote = "Auto-approved via seed data.",
                            ReviewedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Verified",
                            SubmittedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VerificationId = new Guid("00000000-0000-0000-0000-000000000031"),
                            IdDocumentRef = "seed/id-document-owner2.pdf",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000004"),
                            PersonalInformation = "Nguyen Van Minh – ID verified for seeding purposes.",
                            ReviewNote = "Auto-approved via seed data.",
                            ReviewedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Verified",
                            SubmittedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VerificationId = new Guid("00000000-0000-0000-0000-000000000032"),
                            IdDocumentRef = "seed/id-document-owner3.pdf",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000005"),
                            PersonalInformation = "Tran Thi Lan – ID verified for seeding purposes.",
                            ReviewNote = "Auto-approved via seed data.",
                            ReviewedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Verified",
                            SubmittedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VerificationId = new Guid("00000000-0000-0000-0000-000000000033"),
                            IdDocumentRef = "seed/id-document-owner4.pdf",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000006"),
                            PersonalInformation = "Le Hoang Nam – ID verified for seeding purposes.",
                            ReviewNote = "Auto-approved via seed data.",
                            ReviewedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Verified",
                            SubmittedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VerificationId = new Guid("00000000-0000-0000-0000-000000000034"),
                            IdDocumentRef = "seed/id-document-owner5.pdf",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000007"),
                            PersonalInformation = "Pham Thi Thu – ID verified for seeding purposes.",
                            ReviewNote = "Auto-approved via seed data.",
                            ReviewedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Verified",
                            SubmittedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Hmss.Api.Entities.Property", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralPolicies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MapLocation")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PropertyId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Address = "123 Nguyen Hue Street, District 1, Ho Chi Minh City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A comfortable hostel located in the heart of the city with easy access to transportation.",
                            GeneralPolicies = "No smoking indoors. Quiet hours from 10 PM to 7 AM. Guests must register at front desk.",
                            Name = "Sunrise Hostel",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Address = "45 Tran Hung Dao Street, Hoan Kiem District, Hanoi",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern residences near Hoan Kiem Lake with excellent public transport links.",
                            GeneralPolicies = "No parties or loud music. Pets not allowed. Monthly electricity billed separately.",
                            Name = "Central Park Residences",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000004"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Address = "78 Bui Vien Street, District 1, Ho Chi Minh City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Vibrant hostel on the famous backpacker street. Walking distance to Ben Thanh Market.",
                            GeneralPolicies = "Curfew at midnight. No cooking in rooms. ID required at check-in.",
                            Name = "Saigon Garden Hostel",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000005"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Address = "12 Vo Nguyen Giap Street, Son Tra District, Da Nang",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Peaceful guesthouse 5 minutes walk from My Khe Beach with sea breeze views.",
                            GeneralPolicies = "No sandy shoes inside. Towels provided. Checkout by 11 AM.",
                            Name = "Beachside Retreat",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000005"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Address = "34 Phan Dinh Phung Street, Da Lat City, Lam Dong",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cozy highland lodge surrounded by pine forests. Cool climate year-round.",
                            GeneralPolicies = "Blankets and heater provided. No campfires on premises. Respect quiet hours 9 PM onward.",
                            Name = "Mountain View Lodge",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000006"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Address = "56 Nguyen Tat Thanh Street, District 4, Ho Chi Minh City",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Budget-friendly house near HCMC University of Technology. Ideal for students.",
                            GeneralPolicies = "Students preferred. Study quiet hours from 8 PM to 6 AM. Shared kitchen available.",
                            Name = "University Quarter House",
                            OwnerId = new Guid("00000000-0000-0000-0000-000000000007"),
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Hmss.Api.Entities.RentalRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BudgetExpectation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpectedRentalDuration")
                        .HasColumnType("int");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("MoveInDate")
                        .HasColumnType("date");

                    b.Property<int>("OccupantCount")
                        .HasColumnType("int");

                    b.Property<string>("OccupationCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredContactMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SpecialNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RequestId");

                    b.HasIndex("ListingId");

                    b.HasIndex("TenantId");

                    b.ToTable("RentalRequests", t =>
                        {
                            t.HasCheckConstraint("CK_RentalRequest_Status", "Status IN ('Pending', 'Accepted', 'Rejected', 'CancelledByTenant', 'RevokedByOwner')");
                        });
                });

            modelBuilder.Entity("Hmss.Api.Entities.RoomListing", b =>
                {
                    b.Property<Guid>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("AvailableFrom")
                        .HasColumnType("date");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FurnishedStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImagesRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PrivateWCStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ListingId");

                    b.HasIndex("PropertyId");

                    b.ToTable("RoomListings", t =>
                        {
                            t.HasCheckConstraint("CK_RoomListing_FurnishedStatus", "FurnishedStatus IN ('FullyFurnished', 'PartiallyFurnished', 'Unfurnished')");

                            t.HasCheckConstraint("CK_RoomListing_PrivateWCStatus", "PrivateWCStatus IN ('Private', 'Shared', 'None')");

                            t.HasCheckConstraint("CK_RoomListing_Status", "Status IN ('Draft', 'PublishedAvailable', 'Locked', 'Hidden', 'Archived')");
                        });

                    b.HasData(
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-000000000020"),
                            Amenities = "[\"WiFi\",\"Air Conditioning\",\"Water Heater\",\"Desk\"]",
                            AvailableFrom = new DateOnly(2026, 2, 1),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A bright single room on the 3rd floor with a window overlooking the city.",
                            FurnishedStatus = "FullyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\",\"https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800\"]",
                            Price = 3500000m,
                            PrivateWCStatus = "Private",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000010"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Cozy Single Room – City View",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-000000000021"),
                            Amenities = "[\"WiFi\",\"Fan\",\"Shared Kitchen\"]",
                            AvailableFrom = new DateOnly(2026, 2, 1),
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A spacious double room shared with one other tenant. Great for budget travelers.",
                            FurnishedStatus = "PartiallyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800\",\"https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800\"]",
                            Price = 2200000m,
                            PrivateWCStatus = "Shared",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000010"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Shared Double Room – Budget Stay",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-000000000022"),
                            Amenities = "[\"WiFi\",\"Air Conditioning\",\"Private Bathroom\",\"Mini Fridge\",\"Smart TV\"]",
                            AvailableFrom = new DateOnly(2026, 2, 1),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bright studio apartment with large windows and lake view on the 5th floor.",
                            FurnishedStatus = "FullyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800\",\"https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800\",\"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800\"]",
                            Price = 5500000m,
                            PrivateWCStatus = "Private",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000011"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Modern Studio – Hoan Kiem View",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-000000000023"),
                            Amenities = "[\"WiFi\",\"Air Conditioning\",\"Wardrobe\",\"Hot Water\"]",
                            AvailableFrom = new DateOnly(2026, 3, 1),
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Twin beds, ideal for two colleagues or travel partners. Very central location.",
                            FurnishedStatus = "FullyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1585128792020-803d29415281?w=800\",\"https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=800\"]",
                            Price = 4200000m,
                            PrivateWCStatus = "Shared",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000011"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Twin Bedroom – City Centre",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-000000000024"),
                            Amenities = "[\"WiFi\",\"Air Conditioning\",\"En-suite Bathroom\",\"Locker\"]",
                            AvailableFrom = new DateOnly(2026, 2, 15),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "En-suite private room in the heart of the backpacker district. Vibrant nightlife outside.",
                            FurnishedStatus = "FullyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800\",\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1590490360182-c33d7aaf884d?w=800\"]",
                            Price = 3800000m,
                            PrivateWCStatus = "Private",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000012"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Private Room – Backpacker Hub",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-000000000025"),
                            Amenities = "[\"WiFi\",\"Fan\",\"Locker\",\"Reading Light\",\"Shared Bathroom\"]",
                            AvailableFrom = new DateOnly(2026, 2, 1),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Comfortable bunk bed in a clean mixed dorm. Lockers and individual reading lights included.",
                            FurnishedStatus = "PartiallyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800\",\"https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800\"]",
                            Price = 1200000m,
                            PrivateWCStatus = "Shared",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000012"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Dorm Bed – Mixed 6-Bed Room",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-000000000026"),
                            Amenities = "[\"WiFi\",\"Air Conditioning\",\"Beach Towels\",\"Balcony\",\"Hot Water\"]",
                            AvailableFrom = new DateOnly(2026, 3, 1),
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Airy double room with ocean breeze. Just a short stroll to My Khe Beach.",
                            FurnishedStatus = "FullyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\",\"https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800\",\"https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800\"]",
                            Price = 4500000m,
                            PrivateWCStatus = "Private",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000013"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Sea Breeze Double Room",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-000000000027"),
                            Amenities = "[\"WiFi\",\"Fan\",\"Shared Bathroom\"]",
                            AvailableFrom = new DateOnly(2026, 2, 1),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Simple, clean single room for solo travellers on a budget near the beach.",
                            FurnishedStatus = "PartiallyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=800\",\"https://images.unsplash.com/photo-1590490360182-c33d7aaf884d?w=800\"]",
                            Price = 2500000m,
                            PrivateWCStatus = "Shared",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000013"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Budget Single – Ground Floor",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-000000000028"),
                            Amenities = "[\"WiFi\",\"Heater\",\"Fireplace\",\"Private Bathroom\",\"Coffee Maker\",\"Garden View\"]",
                            AvailableFrom = new DateOnly(2026, 2, 1),
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Romantic suite with large windows overlooking pine forests. Fireplace included.",
                            FurnishedStatus = "FullyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800\",\"https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800\",\"https://images.unsplash.com/photo-1585128792020-803d29415281?w=800\"]",
                            Price = 6000000m,
                            PrivateWCStatus = "Private",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000014"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Pine Forest Suite",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-000000000029"),
                            Amenities = "[\"WiFi\",\"Heater\",\"Hot Water\",\"Desk\"]",
                            AvailableFrom = new DateOnly(2026, 3, 1),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warm single room with thick blankets and mountain air. Perfect for a quiet retreat.",
                            FurnishedStatus = "FullyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800\",\"https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800\"]",
                            Price = 3200000m,
                            PrivateWCStatus = "Shared",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000014"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Cosy Highland Single",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-00000000002a"),
                            Amenities = "[\"WiFi\",\"Air Conditioning\",\"Desk\",\"Bookshelf\",\"Hot Water\"]",
                            AvailableFrom = new DateOnly(2026, 2, 1),
                            Capacity = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Quiet study room ideal for university students. Desk, bookshelf, and fast WiFi provided.",
                            FurnishedStatus = "FullyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800\",\"https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800\",\"https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800\"]",
                            Price = 2800000m,
                            PrivateWCStatus = "Shared",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000015"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Student Room – Near HCMC University",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ListingId = new Guid("00000000-0000-0000-0000-00000000002b"),
                            Amenities = "[\"WiFi\",\"Fan\",\"2 Desks\",\"Shared Kitchen\",\"Laundry Access\"]",
                            AvailableFrom = new DateOnly(2026, 2, 1),
                            Capacity = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Affordable shared room for two students. Separate study desks and personal storage.",
                            FurnishedStatus = "PartiallyFurnished",
                            ImagesRef = "[\"https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800\",\"https://images.unsplash.com/photo-1609766857041-ed402ea8069a?w=800\"]",
                            Price = 1800000m,
                            PrivateWCStatus = "Shared",
                            PropertyId = new Guid("00000000-0000-0000-0000-000000000015"),
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PublishedAvailable",
                            Title = "Shared Room – 2 Students",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Hmss.Api.Entities.UserAccount", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserAccounts", t =>
                        {
                            t.HasCheckConstraint("CK_UserAccount_AccountStatus", "AccountStatus IN ('Active', 'Suspended', 'Disabled')");

                            t.HasCheckConstraint("CK_UserAccount_Role", "Role IN ('Tenant', 'Owner', 'SystemAdmin')");
                        });

                    b.HasData(
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000001"),
                            AccountStatus = "Active",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@hmss.local",
                            FullName = "System Administrator",
                            PasswordHash = "$2a$11$.xiHVGhdLQuhJju6xaikaup9tH3uMKd9bh6KtvXn80Se6P3adwNJC",
                            Phone = "0000000000",
                            Role = "SystemAdmin"
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000002"),
                            AccountStatus = "Active",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner@hmss.local",
                            FullName = "Demo Owner",
                            PasswordHash = "$2a$11$/4dlW08KauFF1OFfP7r79OpYl28zJKu8.4oCpV2WTWsCHP2Xso0XS",
                            Phone = "0901234567",
                            Role = "Owner"
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000003"),
                            AccountStatus = "Active",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "tenant@hmss.local",
                            FullName = "Demo Tenant",
                            PasswordHash = "$2a$11$A39f14qYzTS2zbyjpjq/zO0MFhDGBTTnerrwTUEO/qhTqeKuEINne",
                            Phone = "0912345678",
                            Role = "Tenant"
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000004"),
                            AccountStatus = "Active",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner2@hmss.local",
                            FullName = "Nguyen Van Minh",
                            PasswordHash = "$2a$11$PcJPJUrOLexSnouaA5M48u9ESS2e.llBwlfwh8pOgRFB4EN8.bqkC",
                            Phone = "0902345678",
                            Role = "Owner"
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000005"),
                            AccountStatus = "Active",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner3@hmss.local",
                            FullName = "Tran Thi Lan",
                            PasswordHash = "$2a$11$LhPSDwlEcrr9wWxVnHhW6OUNbuns40Ic3HDJ1DggUrPhg0V/x6bGa",
                            Phone = "0903456789",
                            Role = "Owner"
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000006"),
                            AccountStatus = "Active",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner4@hmss.local",
                            FullName = "Le Hoang Nam",
                            PasswordHash = "$2a$11$bvOgpfP3d60bMofO5x1bgeJexkHpDYo52.aeiaN8rqxRjAPjBMXZm",
                            Phone = "0904567890",
                            Role = "Owner"
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000007"),
                            AccountStatus = "Active",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner5@hmss.local",
                            FullName = "Pham Thi Thu",
                            PasswordHash = "$2a$11$pbMw3Xp3WeS2iP9ElFOsyuCLi3RM3I7Gsms03J.PdudrfEzfXKmga",
                            Phone = "0905678901",
                            Role = "Owner"
                        });
                });

            modelBuilder.Entity("Hmss.Api.Entities.ChatMessage", b =>
                {
                    b.HasOne("Hmss.Api.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Hmss.Api.Entities.RentalRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Hmss.Api.Entities.UserAccount", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Request");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Hmss.Api.Entities.Conversation", b =>
                {
                    b.HasOne("Hmss.Api.Entities.UserAccount", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Hmss.Api.Entities.RentalRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Hmss.Api.Entities.UserAccount", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Request");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Hmss.Api.Entities.OwnerVerification", b =>
                {
                    b.HasOne("Hmss.Api.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Hmss.Api.Entities.Property", b =>
                {
                    b.HasOne("Hmss.Api.Entities.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Hmss.Api.Entities.RentalRequest", b =>
                {
                    b.HasOne("Hmss.Api.Entities.RoomListing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Hmss.Api.Entities.UserAccount", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Hmss.Api.Entities.RoomListing", b =>
                {
                    b.HasOne("Hmss.Api.Entities.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });
#pragma warning restore 612, 618
        }
    }
}
